server:
  port: 8889

spring:
  redis:
    host: 192.168.2.159
    port: 6379
    password: iPwd@201712
  thymeleaf:
    enabled: true
    cache: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

dubbo:
  registry:
    address: 192.168.2.159:2181