server:
  port: 10003

spring:
  redis:
    host: 192.168.2.222
    port: 6379
    password: 123456
  data:
    mongodb:
      host: dds-uf660704d5f162941848-pub.mongodb.rds.aliyuncs.com
      port: 3717
      database: metadata_access
      username: md_recorder
      password: A&Ni8HOu9#nn!0kJ
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.222:3306/mis?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: mis
    password: mis123456
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mingdong.mis.domain.entity

dubbo:
  protocol:
    port: 33002
  registry:
    address: 192.168.2.222:2181
