server:
  port: 80

spring:
  redis:
    host: 10.31.0.108
    port: 6379
    password: 123456
  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

dubbo:
  registry:
    address: 10.31.0.105:2181