server:
  port: 8801

spring:
  redis:
    host: 192.168.2.222
    port: 6379
    password: 123456
  kafka:
    producer:
      bootstrap-servers: 192.168.2.222:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.222:3306/mis?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: mis
    password: mis123456

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mingdong.mis.domain.entity

mongodb:
  analysis:
    uri: mongodb://metadata:123456@192.168.2.222:27017/metadata
  transaction:
    uri: mongodb://metadata:123456@192.168.2.222:27017/metadata

dubbo:
  protocol:
    port: 9901
  registry:
    address: 192.168.2.222:2181
