server:
  port: 80

spring:
  redis:
    host: 192.168.2.139
    port: 6379
    password: 123456
  thymeleaf:
    enabled: true
    cache: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

node:
  id: 1
dubbo:
  registry:
    address: 192.168.2.139:2181
