server:
  port: 80
### mysql & redis connection
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.154.110:3306/mis?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: iPwd@201712
  redis:
    host: 47.96.15.125
    port: 6379
    password: iPwd@201712
  thymeleaf:
    enabled: true
    cache: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
### mybatis config
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.movek.mis.domain.entity
### system param
node:
  id: 1
dubbo:
  protocol:
    port: 33001
  registry:
    address: 47.96.154.110:2181
