server:
  port: 8280

spring:
  redis:
    host: s2.mingdong.com
    port: 6379
    password: Zd4^GarJSA*PUDD0
  thymeleaf:
    enabled: true
    cache: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6573l2hb9rck347.mysql.rds.aliyuncs.com:3306/matedata_stats?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: matedata_stats
    password: r4S!&cyuQ&dN5z*s

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mingdong.mis.domain.entity

dubbo:
  registry:
    address: s4.mingdong.com:2181
