server:
  port: 10004

spring:
  redis:
    host: 192.168.2.222
    port: 6379
    password: 123456
  kafka:
    consumer:
      bootstrap-servers: 192.168.2.222:9092
      group-id: matedata
      auto-offset-reset: earliest

dubbo:
  protocol:
    port: 33002
  registry:
    address: 192.168.2.222:2181