server:
  port: 8801

spring:
  redis:
    host: s4.mingdong.com
    port: 6379
    password: UPKxSxCJBte&Mb@t
  kafka:
    producer:
      bootstrap-servers: s4.mingdong.com:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6573l2hb9rck347.mysql.rds.aliyuncs.com:3306/matedata?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: matedata
    password: JC@48*E!QxA&#CKH

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mingdong.mis.domain.entity

mongodb:
  analysis:
    uri: mongodb://matedata:A&Ni8HOu9#nn!0kJ@dds-uf660704d5f162941.mongodb.rds.aliyuncs.com:3717,dds-uf660704d5f162942.mongodb.rds.aliyuncs.com:3717/metadata?replicaSet=mgset-5409523
  transaction:
    uri: mongodb://matedata:A&Ni8HOu9#nn!0kJ@dds-uf660704d5f162941.mongodb.rds.aliyuncs.com:3717,dds-uf660704d5f162942.mongodb.rds.aliyuncs.com:3717/matedata?replicaSet=mgset-5409523

dubbo:
  protocol:
    port: 9901
  registry:
    address: s4.mingdong.com:2181
