server:
  port: 10000

spring:
  redis:
    host: 10.31.0.105
    port: 6379
    password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6573l2hb9rck347.mysql.rds.aliyuncs.com:3306/mis?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: mis
    password: mis123456

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mingdong.mis.domain.entity

mongodb:
  analysis:
    uri: mongodb://md_recorder:A&Ni8HOu9#nn!0kJ@dds-uf660704d5f162941848-pub.mongodb.rds.aliyuncs.com:3717/metadata
  transaction:
    uri: mongodb://md_recorder:A&Ni8HOu9#nn!0kJ@dds-uf660704d5f162941848-pub.mongodb.rds.aliyuncs.com:3717/metadata_access

dubbo:
  protocol:
    port: 33002
  registry:
    address: 10.31.0.105:2181
